name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: action/setup-node@v3
        with:
          node-version: '14'
      - run: npm run eslint